export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const ADD_ORDER_TO_CART = 'ADD_ORDER_TO_CART';

export const FETCH_PRODUCT_BY_ID_START = 'FETCH_PRODUCT_BY_ID_START';
export const FETCH_PRODUCT_BY_ID_SUCCESS = 'FETCH_PRODUCT_BY_ID_SUCCESS';
export const FETCH_PRODUCT_BY_ID_FAILURE = 'FETCH_PRODUCT_BY_ID_FAILURE';

export const FETCH_PRODUCT_BY_TAG_START = 'FETCH_PRODUCT_BY_TAG_START';
export const FETCH_PRODUCT_BY_TAG_SUCCESS = 'FETCH_PRODUCT_BY_TAG_SUCCESS';
export const FETCH_PRODUCT_BY_TAG_FAILURE = 'FETCH_PRODUCT_BY_TAG_FAILURE';

export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const REMOVE_ONE_ITEM_FROM_CART = 'REMOVE_ONE_ITEM_FROM_CART';

export const SUBMIT_ORDER_TO_SERVER = 'SUBMIT_ORDER_TO_SERVER';
export const CART_EMPTY = "CART_EMPTY";
export const ORDER_SUBMITED = "ORDER_SUBMITED";
export const NEW_ORDER = "NEW_ORDER";
export const TAG_SELECTED = "TAG_SELECTED";
